language: node_js
node_js:
- '0.10'
install:
- npm install
before_script:
- npm install -g bower grunt-cli
- bower install
- gem install compass
script:
- grunt build
after_success:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- grunt deploy
env:
  global:
    secure: NqjRbj2FyDFxw5lTaG/JC4gVegA/7c7TFZdsGlu3bKfCCZPqokeIjoJnR2q69EkxNtqo5kZU0TogJBPEAKwXbZDSuufjrnPzOCf0CjmgwZ4GMXQ1Xd1smEtACpp+fMZT3h027pA9HFFbedPO+fQ4rYSrRDw9RQsIo9yBmB2Bnvk=
